### ISSUE TITLE
Unable to get Optunity to work on Windows 10

### ISSUE THREAD

**Issue by webzest** [claesenm/optunity#101] opened 2020-07-03 11:29 UTC
I have tried to get Optunity to work on two of my Windows 10 PCs without success.  I followed the instructions to install from GIT, added the PYTHONPATH to my System environment and also added the optunity folder to my  path.  However, optunity only works on the python files that are inside the optunity example folders.  I even tried to drag my own files that I need to process or tune with optunity, but then the python import call does not find the package.  Is there any way to have a more detailed windows direction with line-by-line steps that are more in line with a dummies like myself?  Thank you for your wonderful code and solution to the hyperparameter tuning 

here is a screen capture of two separate folders with the same code, where one recognizes the import and the other does not.
[Link to png sample setup](https://webzest.com/optunityissue.png)

**Comment by jaak-s** [comment] 2020-07-03 12:38
Good idea to try to re-install Python. If you didn't try, I recommend using out Anaconda installation.
Also might be a good idea to try installing it with `pip install optunity`?

**Comment by webzest** [comment] 2020-07-03 12:45
I spent a whole day trying every possible combination.  I have Anaconda3 and only use the Anaconda CMD as administrator to create new environments to add all the necessay libraries for projects.  I have also updated my system environment with PYTHONPATH that is ointing to the conda environment that I created for the project.  I used pip to install opotunity as well as the setup.py approach.  I was just trying to determine if there is something else that i am missing and wanted a clean step-by-step direction that is not pointing me to a bunch of different locations to get files and updating paths...

**Comment by jaak-s** [comment] 2020-07-03 13:49
Often the issue is that there are several pythons installed in parallel and the one you are using is not the one that one where optunity is installed. So perhaps a good thing to try is to remove all pythons/anacondas, so that no python can be executed. And then install one and install optunity to it.

**Comment by webzest** [comment] 2020-07-03 15:17
Hi Jaak-s,

I uninstalled all traces of python and rebooted my system.  then, I installed a Miniconda3, created a brand new environment.  Installed the required libraries and launched VSCode with the py file.  There were no errors in the import area and VSCode had a clean python 3.7.7 load.  Finally, I ran the code to the point where I am calling the optunity library.  When it reached the 
`hps, _, _ = opt.maximize(svm_auc, num_evals=200, logC=[-5, 2], logGamma=[-5, 1])` it generated the following:

`>>> # score function: twice iterated 10-fold cross-validated accuracy
>>> 
>>> @opt.cross_validated(x=X_train, y=y_train, num_folds=10, num_iter=2)
... def svm_auc(X_train, y_train, X_test, y_test, logC, logGamma):
...     model = sklearn.svm.SVC(C=10 ** logC, gamma=10 ** logGamma).fit(X_train, y_train)
...     decision_values = model.decision_function(X_test)
...     return opt.metrics.roc_auc(y_test, decision_values)
... # perform tuning
...
>>> hps, _, _ = opt.maximize(svm_auc, num_evals=200, logC=[-5, 2], logGamma=[-5, 1])
Traceback (most recent call last):
  File "c:\optunity\optunity\cross_validation.py", line 77, in select
    return collection[indices, ...]
  File "C:\Users\johnny\.conda\envs\tsf\lib\site-packages\pandas\core\frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\johnny\.conda\envs\tsf\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 109, in pandas._libs.index.IndexEngine.get_loc
TypeError: '([779, 48, 553, 497, 546, 559, 201, 58, 448, 393, 820, 512, 871, 445, 125, 416, 602, 132, 293, 731, 610, 64, 582, 221, 28, 198, 121, 633, 36, 69, 668, 695, 318, 441, 341, 710, 406, 634, 340, 463, 395, 676, 27, 707, 958, 357, 801, 317, 619, 303, 325, 10, 31, 620, 656, 281, 264, 204, 267, 309, 205, 943, 203, 481, 877, 932, 890, 724, 82, 507, 110, 960, 112, 895, 749, 875, 485, 563, 312, 380, 922, 843, 214, 528, 284, 163, 471, 331, 671, 552, 831, 290, 461, 358, 887, 542, 937, 403, 26, 853, 539, 722, 375, 936, 118, 433, 156, 627, 762, 726, 94, 920, 739, 791, 232, 297, 665, 755, 653, 98, 32, 794, 248, 423, 355, 314, 451, 572, 164, 84, 796, 770, 501, 250, 966, 307, 351, 545, 771, 296, 376, 927, 409, 53, 378, 81, 586, 212, 678, 698, 525, 399, 959, 280, 854, 206, 359, 180, 139, 482, 158, 556, 2, 22, 969, 607, 7, 388, 138, 740, 870, 428, 23, 425, 712, 453, 748, 60, 827, 363, 498, 944, 370, 716, 547, 772, 137, 371, 289, 322, 506, 935, 646, 962, 379, 332, 37, 934, 262, 108, 778, 320, 256, 822, 580, 354, 825, 483, 730, 703, 533, 898, 614, 174, 76, 577, 285, 182, 315, 593, 704, 561, 421, 75, 353, 51, 660, 236, 186, 575, 117, 349, 381, 537, 382, 128, 405, 709, 5, 534, 538, 599, 263, 923, 767, 150, 834, 413, 684, 845, 218, 368, 830, 313, 833, 555, 608, 116, 398, 364, 259, 494, 444, 328, 260, 208, 809, 859, 122, 305, 56, 153, 266, 683, 41, 450, 699, 688, 40, 181, 12, 265, 66, 931, 195, 868, 617, 714, 447, 333, 908, 258, 101, 113, 114, 268, 941, 685, 480, 743, 65, 914, 938, 231, 29, 899, 905, 808, 323, 92, 817, 526, 21, 247, 414, 515, 91, 245, 46, 948, 404, 566, 468, 457, 191, 211, 777, 
288, 574, 352, 849, 517, 626, 170, 151, 496, 271, 304, 855, 96, 273, 59, 612, 945, 864, 147, 812, 805, 636, 199, 821, 47, 166, 188, 823, 562, 200, 909, 223, 397, 907, 729, 175, 35, 886, 597, 387, 569, 446, 694, 49, 896, 692, 392, 63, 604, 583, 790, 708, 862, 658, 560, 308, 475, 106, 872, 954, 971, 350, 925, 503, 587, 758, 721, 78, 366, 733, 781, 858, 851, 324, 227, 55, 30, 861, 459, 930, 689, 491, 254, 713, 624, 663, 915, 815, 455, 299, 484, 435, 904, 541, 390, 613, 160, 902, 558, 850, 594, 237, 171, 840, 109, 752, 79, 760, 532, 644, 747, 725, 609, 623, 919, 950, 269, 946, 460, 697, 766, 193, 746, 43, 675, 836, 753, 159, 691, 33, 238, 761, 142, 576, 347, 649, 45, 878, 190, 605, 343, 666, 690, 686, 146, 807, 50, 24, 657, 968, 536, 590, 885, 278, 728, 571, 508, 335, 148, 652, 456, 956, 745, 489, 83, 488, 847, 837, 585, 129, 510, 157, 754, 893, 93, 975, 751, 818, 622, 662, 39, 720, 549, 616, 443, 396, 635, 6, 342, 876, 500, 412, 601, 338, 568, 165, 469, 705, 933, 419, 235, 567, 466, 882, 631, 674, 912, 810, 143, 141, 242, 474, 192, 680, 596, 11, 239, 816, 595, 454, 916, 522, 178, 234, 462, 581, 910, 374, 783, 13, 233, 531, 130, 520, 229, 504, 814, 826, 367, 493, 786, 900, 803, 144, 372, 867, 472, 127, 161, 17, 535, 965, 334, 330, 964, 564, 799, 100, 300, 38, 835, 179, 970, 841, 119, 903, 470, 464, 952, 386, 924, 509, 319, 54, 224, 95, 495, 251, 757, 838, 316, 711, 889, 337, 540, 615, 20, 213, 209, 123, 811, 111, 420, 172, 869, 243, 72, 465, 785, 257, 126, 949, 897, 592, 554, 107, 797, 410, 787, 832, 131, 400, 523, 216, 230, 544, 768, 401, 603, 70, 8, 311, 800, 249, 514, 362, 276, 115, 639, 637, 548, 742, 669, 702, 598, 244, 951, 963, 804, 883, 667, 255, 9, 207, 183, 329, 415, 326, 611, 361, 863, 467, 57, 492, 458, 476, 279, 384, 573, 90, 642, 839, 701, 225, 687, 176, 301, 543, 499, 73, 429, 103, 706, 105, 310, 723, 473, 939, 769, 104, 776, 888, 89, 346, 589, 427, 184, 584, 848, 202, 348, 918, 734, 440, 173, 795, 906, 272, 430, 693, 411, 490, 61, 344, 270, 215, 630, 806, 68, 641, 527, 275, 140, 953, 844, 294, 670, 154, 1, 253, 67, 765, 654, 187, 52, 881, 879, 673, 327, 955, 169, 719, 149, 487, 773, 431, 775, 408, 655, 947, 228, 792, 16, 217, 529, 25, 252, 891, 578, 647, 85, 718, 432, 819, 502, 570, 222, 518, 3, 717, 282, 292, 798, 219, 511, 600, 15, 789, 638, 373, 442, 824, 856, 286, 645, 884, 177, 136, 88, 369, 438, 917, 738, 155, 672, 120, 424, 744, 439, 852, 732, 846, 194, 437, 336, 417, 727, 74, 857, 865, 34, 0, 62, 621, 894, 913, 659, 632, 681, 77, 407, 168, 452, 650, 360, 210, 873, 972, 802, 664, 521, 880, 929, 828, 784, 298, 618, 422, 911, 640, 973, 550, 591, 449, 124, 19, 921, 277, 436, 152, 97, 102, 682, 901, 356, 220, 961, 565, 196, 842, 679, 892], Ellipsis)' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johnny\.conda\envs\tsf\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 779

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\optunity\optunity\api.py", line 181, in maximize
    pmap=pmap)
  File "c:\optunity\optunity\api.py", line 245, in optimize
    solution, report = solver.optimize(f, maximize, pmap=pmap)
  File "c:\optunity\optunity\solvers\ParticleSwarm.py", line 271, in optimize
    for part, fitness in zip(pop, fitnesses):
  File "c:\optunity\optunity\solvers\ParticleSwarm.py", line 259, in evaluate
    return f(**d)
  File "c:\optunity\optunity\functions.py", line 301, in wrapped_f
    value = f(*args, **kwargs)
  File "c:\optunity\optunity\functions.py", line 356, in wrapped_f
    return f(*args, **kwargs)
  File "c:\optunity\optunity\constraints.py", line 151, in wrapped_f
    return f(*args, **kwargs)
  File "c:\optunity\optunity\constraints.py", line 129, in wrapped_f
    return f(*args, **kwargs)
  File "c:\optunity\optunity\constraints.py", line 266, in func
    return f(*args, **kwargs)
  File "c:\optunity\optunity\cross_validation.py", line 403, in __call__
    kwargs['x_train'] = select(self.x, rows_train)
  File "c:\optunity\optunity\cross_validation.py", line 84, in select
    return [collection[i] for i in indices]
  File "c:\optunity\optunity\cross_validation.py", line 84, in <listcomp>
    return [collection[i] for i in indices]
  File "C:\Users\johnny\.conda\envs\tsf\lib\site-packages\pandas\core\frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\johnny\.conda\envs\tsf\lib\site-packages\pandas\core\indexes\base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 779`

**Comment by jaak-s** [comment] 2020-07-03 17:10
I see no issues related to `optunity` installation anymore. I think we can close this issue.

This error seems to be related to use of DataFrame. Please try converting the data to numpy arrays, e.g., using `df.values`, I think it should work then.

**Comment by webzest** [comment] 2020-07-03 17:49
Hi Jaak,

I tried to convert the train and test data to numpy and still get the same error:

`>>> y_train = copy.copy(y_train.values)
>>> y_test = copy.copy(y_test.values)
>>> X_tX_testrain = copy.copy(X_test.values)
>>> def rmsle_cv(model):
...     kf = KFold(n_folds, random_state=42).get_n_splits(train.values)
...     rmse= np.sqrt(-cross_val_score(model, train.values, y_train, scoring="neg_mean_squared_error", cv = kf))
...     return(rmse)
...
>>> def rmsle(y, y_pred):
...     return np.sqrt(mean_squared_error(y, y_pred))
...
>>> results = []
>>>
>>> names = []
>>> # score function: twice iterated 10-fold cross-validated accuracy
>>>
>>> @opt.cross_validated(x=train, y=y_train, num_folds=10, num_iter=2)
... def svm_auc(X_train, y_train, X_test, y_test, logC, logGamma):
...     model = sklearn.svm.SVC(C=10 ** logC, gamma=10 ** logGamma).fit(X_train, y_train)
...     decision_values = model.decision_function(X_test)
...     return opt.metrics.roc_auc(y_test, decision_values)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\optunity\optunity\cross_validation.py", line 486, in cross_validated
    assert(y is None or len(y) == len(x))
AssertionError
>>>`

**Comment by jaak-s** [comment] 2020-07-03 19:34
This seems a different error, previously the error was
```
File "c:\optunity\optunity\cross_validation.py", line 77, in select
return collection[indices, ...]
```

Now the error looks to be that `x` and `y` are not the same size.

**Comment by webzest** [comment] 2020-07-09 12:06
Unable to get this to work on R.  So, I am closing this case for lack of functionality.

**Closed as completed** 2020-07-09 12:05 UTC
